server:
  port: 8100

spring:
 # application:
  #  name: foa-customer
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/foa-customer}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:root123}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    username: foa
    password: foa

  cloud:
    #without function definition the listener is not working so I had to add it
    function:
      definition: newOrderCreated
    stream:
      bindings:
        newOrderCreated-in-0:
          destination: ordercreated-events


eureka:
#  instance:
 #   hostname: ${EUREKA_SERVER_HOST:localhost}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}
