server:
  port: 8200

eureka:
#  instance:
 #   hostname: ${EUREKA_SERVER_HOST:localhost}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}

spring:
  data:
    mongodb:
      database: food-order-app-restaurant
      uri: mongodb://localhost:27017